### ISSUE TITLE
Return a message when an error is thrown and !hol is unable to retrieve

### ISSUE THREAD

**Issue by j-salvador** [j-salvador/HolidayBot98#1]
currently it just leaves chat log blank, and waits for next user action

**Comment by j-salvador** [comment]
So far happens when Russian cities are retrieved.

['RS', "Bol'shoy Kashelak\n"]
Country code: RS
City: Bol'shoy Kashelak
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/bot-admin/.local/lib/python3.6/site-packages/discord/client.py", line 307, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "main.py", line 176, in on_message
    await client.send_message(message.channel, generate_scenario())
  File "main.py", line 77, in generate_scenario
    country = get_country_from_code(country_code)
  File "main.py", line 51, in get_country_from_code
    return line.split('\t')[1][:-1]  # remove \n character by slicing
IndexError: list index out of range
